branches:
  - main

plugins:
  # Analyze commits to determine release type
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        # Major (breaking changes)
        - breaking: true
          release: major

        # Minor (new features)
        - type: feat
          release: minor

        # Patch (fixes and improvements)
        - type: fix
          release: patch
        - type: perf
          release: patch
        - type: refactor
          release: patch
        - type: revert
          release: patch

        # Documentation and maintenance (no release)
        - type: docs
          release: false
        - type: test
          release: false
        - type: ci
          release: false
        - type: chore
          release: false
        - type: build
          release: false
        - type: style
          release: false

  # Generate release notes
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits

  # Update CHANGELOG.md
  - "@semantic-release/changelog"

  # Publish to npm with OIDC authentication
  - - "@semantic-release/npm"
    - tarballDir: release

  # Create GitHub release with assets
  - - "@semantic-release/github"
    - assets:
        - path: "release/*.tgz"
          label: "npm package"

  # Commit updated files back to repository
  - - "@semantic-release/git"
    - assets:
        - package.json
        - bun.lock
        - CHANGELOG.md
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
